require('omerxx.lazy.keymaps')
-- require('omerxx.lazy.plugins.lazy')
-- require('omerxx.lazy.plugins.misc')
require('omerxx.lazy.plugins.lualine')
require('omerxx.lazy.options')
-- require('omerxx.lazy.misc')
require('omerxx.lazy.plugins.dap')
require('omerxx.lazy.plugins.gitsigns')
require('omerxx.lazy.plugins.tele')
require('omerxx.lazy.plugins.treesitter')
require('omerxx.lazy.plugins.lsp')
-- Note: cmp.lua is handled by theprimeagen.lazy.lsp instead
require('omerxx.lazy.plugins.trouble')
-- require('omerxx.lazy.plugins.obsidian')
require('omerxx.lazy.plugins.zenmode')
require('omerxx.lazy.plugins.neogit')
require('omerxx.lazy.plugins.codesnap')
-- require('omerxx.lazy.plugins.harpoon')
