[config]
version_check = false

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.lua'
output_path = '~/.config/hypr/hyprland/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux/tmux-colors.conf'
output_path = '~/.config/tmux/matugen-colors.conf'

[templates.fish]
input_path = '~/.config/matugen/templates/fish/fish-colors.fish'
output_path = '~/.config/fish/generated-matugen-colors.fish'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty/kitty-colors.conf'
output_path = '~/.config/kitty/matugen-colors.conf'

[templates.cursor_dark]
input_path = '~/.config/matugen/templates/cursor/cursor-dark.json'
output_path = '~/.local/state/quickshell/user/generated/cursor/cursor-dark.json'

[templates.cursor_light]
input_path = '~/.config/matugen/templates/cursor/cursor-light.json'
output_path = '~/.local/state/quickshell/user/generated/cursor/cursor-light.json'
